name: build DoH_amd64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build DoH
      run: |
        chmod +x doh.sh
        sudo ./doh.sh
        
    - name: MV
      run: |
        sudo mkdir -p ./doh
        sudo rm -rf ./doh/doh_s_amd64.zip
        sudo cp -f /usr/local/bin/doh-server ./doh-server
        sudo zip -r doh_s_amd64.zip ./doh-server
        sudo mv -f doh_s_amd64.zip ./doh
        
    - name: Commit
      run: |
        git config --global user.email jacyl4@gmail.com
        git config --global user.name jacyl4
        git add ./doh
        git commit -m "Update doh_amd64" -a
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
