name: Auto NGINX

on:
  workflow_dispatch:

env:
    NGINX_VERSION: 1.19.4

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install dep
      run: |
        sudo export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install --no-install-recommends --no-install-suggests -y ca-certificates wget curl unzip git build-essential cmake autoconf libtool libpcre3-dev zlib1g-dev libatomic-ops-dev

    - name: Build NGINX
      run: |
        chmod +x nginx_amd64.sh
        ./nginx_amd64.sh
        
