name: Auto NGINX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buster
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: build nginx
      run: |
        chmod +x nginx_amd64.sh
        ./nginx_amd64.sh

